services:
  - type: web
    name: ebook-api
    env: python
    region: frankfurt
    plan: free
    # Build aşamasında sadece paketleri kuruyoruz
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    # Start aşamasında önce DB'yi güncelleyip sonra API'yi açıyoruz
    startCommand: "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2 # [cite: 2026-03-28]
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: DEBUG
        value: "false"
      - key: USE_CELERY
        value: "false"
      - key: API_V1_PREFIX
        value: /api/v1
      - key: PROJECT_NAME
        value: eBook API
      - key: MAX_UPLOAD_SIZE
        value: 52428800
      - key: PDF_MAX_PAGES
        value: 1000

      # Gemini
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-3.1-flash-lite-preview
      - key: GEMINI_TEMPERATURE
        value: "0.4"
      - key: GEMINI_MAX_TOKENS
        value: 8192

      # Qdrant
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: QDRANT_COLLECTION_NAME
        value: ebook_blocks
      - key: EMBEDDING_MODEL_NAME
        value: sentence-transformers/all-MiniLM-L6-v2