"""Add BookGlossary and TranslatedBlock models

Revision ID: 39259de093b1
Revises: f8bccfadad0b
Create Date: 2026-03-23 23:20:39.629142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39259de093b1'
down_revision = 'f8bccfadad0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_glossaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('glossary_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id')
    )
    op.create_index(op.f('ix_book_glossaries_id'), 'book_glossaries', ['id'], unique=False)
    op.create_table('translated_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('target_language', sa.String(length=10), nullable=False),
    sa.Column('translated_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['book_blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translated_blocks_block_id'), 'translated_blocks', ['block_id'], unique=False)
    op.create_index(op.f('ix_translated_blocks_id'), 'translated_blocks', ['id'], unique=False)
    op.create_index(op.f('ix_translated_blocks_target_language'), 'translated_blocks', ['target_language'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translated_blocks_target_language'), table_name='translated_blocks')
    op.drop_index(op.f('ix_translated_blocks_id'), table_name='translated_blocks')
    op.drop_index(op.f('ix_translated_blocks_block_id'), table_name='translated_blocks')
    op.drop_table('translated_blocks')
    op.drop_index(op.f('ix_book_glossaries_id'), table_name='book_glossaries')
    op.drop_table('book_glossaries')
    # ### end Alembic commands ###