"""Add BookSummary caching table for summarization

Revision ID: 8446d35bdf86
Revises: 39259de093b1
Create Date: 2026-03-28 17:25:22.736357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8446d35bdf86'
down_revision = '39259de093b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('target_language', sa.String(length=10), nullable=False),
    sa.Column('start_page', sa.Integer(), nullable=True),
    sa.Column('end_page', sa.Integer(), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_summaries_book_id'), 'book_summaries', ['book_id'], unique=False)
    op.create_index(op.f('ix_book_summaries_end_page'), 'book_summaries', ['end_page'], unique=False)
    op.create_index(op.f('ix_book_summaries_id'), 'book_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_book_summaries_start_page'), 'book_summaries', ['start_page'], unique=False)
    op.create_index(op.f('ix_book_summaries_target_language'), 'book_summaries', ['target_language'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_summaries_target_language'), table_name='book_summaries')
    op.drop_index(op.f('ix_book_summaries_start_page'), table_name='book_summaries')
    op.drop_index(op.f('ix_book_summaries_id'), table_name='book_summaries')
    op.drop_index(op.f('ix_book_summaries_end_page'), table_name='book_summaries')
    op.drop_index(op.f('ix_book_summaries_book_id'), table_name='book_summaries')
    op.drop_table('book_summaries')
    # ### end Alembic commands ###