"""Change BookPage to BookBlock for RAG

Revision ID: f8bccfadad0b
Revises: 9b2f3d6d1a10
Create Date: 2026-03-23 16:38:36.890683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8bccfadad0b'
down_revision = '9b2f3d6d1a10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_pages_book_id'), table_name='book_blocks')
    op.drop_index(op.f('ix_book_pages_id'), table_name='book_blocks')
    op.create_index(op.f('ix_book_blocks_book_id'), 'book_blocks', ['book_id'], unique=False)
    op.create_index(op.f('ix_book_blocks_id'), 'book_blocks', ['id'], unique=False)
    op.alter_column('books', 'file_size',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'file_size',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_book_blocks_id'), table_name='book_blocks')
    op.drop_index(op.f('ix_book_blocks_book_id'), table_name='book_blocks')
    op.create_index(op.f('ix_book_pages_id'), 'book_blocks', ['id'], unique=False)
    op.create_index(op.f('ix_book_pages_book_id'), 'book_blocks', ['book_id'], unique=False)
    # ### end Alembic commands ###